#!/usr/bin/env python
from random import choice


def generate_secret(size):
    return ''.join(choice('abcdefghijklmnopqrstuvwxyz0123456789@$%^*-_=+')
                   for i in xrange(size))


if __name__ == '__main__':
    print generate_secret(50)
